import { useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { Mail, Lock, User, ArrowLeft } from 'lucide-react'

export default function RegisterLogin() {
  const [isLogin, setIsLogin] = useState(true) // toggle between login/register
    const [form, setForm] = useState({ name: '', email: '', password: '' })
      const navigate = useNavigate()

        const handleSubmit = (e: React.FormEvent) => {
            e.preventDefault()
                // For now we just fake it and go to dashboard
                    // Later we connect this to Supabase
                        console.log(isLogin ? 'Logging in' : 'Registering', form)
                            navigate('/dashboard')
                              }

                                return (
                                    <div className="min-h-screen flex items-center justify-center bg-gray-50 p-4">
                                          <div className="w-full max-w-md bg-white rounded-2xl shadow-lg p-8">
                                                  
                                                          <Link to="/" className="flex items-center gap-2 text-gray-600 hover:text-black mb-6">
                                                                    <ArrowLeft size={18}/> Back to Home
                                                                            </Link>

                                                                                    <h1 className="text-3xl font-bold text-center mb-2">
                                                                                              {isLogin ? 'Welcome Back' : 'Create Account'}
                                                                                                      </h1>
                                                                                                              <p className="text-gray-500 text-center mb-6">
                                                                                                                        {isLogin ? 'Login to manage your links' : 'Join SocialBoost in 30 seconds'}
                                                                                                                                </p>

                                                                                                                                        {/* Tabs */}
                                                                                                                                                <div className="flex bg-gray-100 rounded-lg p-1 mb-6">
                                                                                                                                                          <button 
                                                                                                                                                                      onClick={() => setIsLogin(true)}
                                                                                                                                                                                  className={`w-1/2 py-2 rounded-md font-semibold transition ${isLogin ? 'bg-white shadow' : 'text-gray-500'}`}>
                                                                                                                                                                                              Login
                                                                                                                                                                                                        </button>
                                                                                                                                                                                                                  <button 
                                                                                                                                                                                                                              onClick={() => setIsLogin(false)}
                                                                                                                                                                                                                                          className={`w-1/2 py-2 rounded-md font-semibold transition ${!isLogin ? 'bg-white shadow' : 'text-gray-500'}`}>
                                                                                                                                                                                                                                                      Sign Up
                                                                                                                                                                                                                                                                </button>
                                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                                {/* Form */}
                                                                                                                                                                                                                                                                                        <form onSubmit={handleSubmit} className="flex flex-col gap-4">
                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                            {!isLogin && (
                                                                                                                                                                                                                                                                                                                        <div className="relative">
                                                                                                                                                                                                                                                                                                                                      <User className="absolute left-3 top-3.5 text-gray-400" size={18}/>
                                                                                                                                                                                                                                                                                                                                                    <input 
                                                                                                                                                                                                                                                                                                                                                                    type="text" 
                                                                                                                                                                                                                                                                                                                                                                                    placeholder="Your Name"
                                                                                                                                                                                                                                                                                                                                                                                                    value={form.name}
                                                                                                                                                                                                                                                                                                                                                                                                                    onChange={e => setForm({...form, name: e.target.value})}
                                                                                                                                                                                                                                                                                                                                                                                                                                    className="w-full pl-10 pr-4 py-3 border rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
                                                                                                                                                                                                                                                                                                                                                                                                                                                    required={!isLogin}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="relative">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <Mail className="absolute left-3 top-3.5 text-gray-400" size={18}/>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <input 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        type="email" 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      placeholder="Email"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    value={form.email}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  onChange={e => setForm({...form, email: e.target.value})}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                className="w-full pl-10 pr-4 py-3 border rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              required
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="relative">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <Lock className="absolute left-3 top-3.5 text-gray-400" size={18}/>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <input 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    type="password" 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  placeholder="Password"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                value={form.password}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              onChange={e => setForm({...form, password: e.target.value})}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            className="w-full pl-10 pr-4 py-3 border rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          required
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <button type="submit" className="w-full py-3 bg-blue-600 text-white font-bold rounded-lg hover:bg-blue-700 transition">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {isLogin ? 'Login' : 'Create Account'}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </form>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }